services:
  api:
    image: devops-assessment-api:${API_TAG}
    container_name: api
    restart: always
    init: true
    env_file: .env
    networks: [backend]
    expose:
      - "8000"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [backend]
    expose:
      - "5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    env_file: .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks: [backend]
    expose:
      - "6379"


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on: [api]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/webroot:/var/www/certbot
    networks: [backend]

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/webroot:/var/www/certbot

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    command:
      - --path.rootfs=/host
    pid: host
    volumes:
      - /:/host:ro,rslave
    networks:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prom_data:/prometheus
    networks:
      - backend

  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}   # later move to .env
      - GF_SERVER_HTTP_PORT=3001
    ports:
      - "3001:3001"   # non-standard port, NOT 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - backend



networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  prom_data:
  grafana_data:
