version = 5.3.1
archive_dir = /etc/letsencrypt/archive/testingproject.online
cert = /etc/letsencrypt/live/testingproject.online/cert.pem
privkey = /etc/letsencrypt/live/testingproject.online/privkey.pem
chain = /etc/letsencrypt/live/testingproject.online/chain.pem
fullchain = /etc/letsencrypt/live/testingproject.online/fullchain.pem
[renewalparams]
account = 4d147888b62c706b28982faa95686406
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
testingproject.online = /var/www/certbot
www.testingproject.online = /var/www/certbot
